### ISSUE TITLE
Accessible CSS colour themes

### ISSUE THREAD

**Issue by sc0ttj** [sc0ttj/mdsh#87]
We already included `colors.css` (https://clrs.cc/) in https://github.com/sc0ttj/mdsh/commit/9a9548ba0b3f1c7b8c2b52811f3a62f086613e51

Let's add some colour themes which give accessible colours (where foreground and background combination has high colour contrast)  

See https://clrs.cc/a11y/

Example:

In `_colors--dark-mode.css`:
```css
/* dark grey bg */
body {
  background: #003411;
}
/* yellow text */
h1,h2,h3,h4,p,li,caption {
  color: #f2e8c2;
}
```
